---
apiVersion: 1

datasources:
  - name: influxdbv2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
