version: "3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.6.1
    env_file:
      - ./.env
    ports:
      - "8086:8086"
    volumes:
      - influxdb2:/var/lib/influxdb2:rw
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    env_file:
      - ./.env
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./conf/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    env_file:
      - ./.env
    links:
      - influxdb
    ports:
      - "57000:57000"
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb2:
