version: "3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.6.1
    env_file:
      - ./influxdb2.env
    ports:
      - "8086:8086"
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    env_file:
      - ./influxdb2.env
    ports:
      - "57000:57000"
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

volumes:
  influxd2:
